[terminal]
shell="fish"
[mouse]

hide_when_typing=true

[general]
import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
    # "~/.config/alacritty/themes/themes/remedy_dark.toml"
    #"~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]

